---
version: "2.0"

services:
  db:
    image: supabase/postgres:15.1.0.73
    env:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data
    expose:
      - port: 5432
        to:
          - service: studio
          - service: api
    params:
      storage:
        data:
          mount: /var/lib/postgresql/data

  api:
    image: supabase/postgrest:v10.1.2
    depends_on:
      - db
    env:
      - PGRST_DB_URI=postgres://postgres:postgres@db:5432/postgres
      - PGRST_DB_SCHEMAS=public
      - PGRST_DB_ANON_ROLE=anon
      - PGRST_JWT_SECRET=super-secret-jwt-token-with-at-least-32-characters
      - PGRST_LOG_LEVEL=info
    expose:
      - port: 3000
        to:
          - service: studio
          - service: gotrue
          - service: realtime
          - service: storage
          - service: meta

  studio:
    image: supabase/studio:20230223-400b5ff
    depends_on:
      - db
      - api
      - gotrue
      - realtime
      - storage
      - meta
    env:
      - STUDIO_PG_META_URL=http://meta:8080
      - POSTGRES_PASSWORD=postgres
      - SUPABASE_URL=http://kong:8000
      - SUPABASE_PUBLIC_URL=${AKASH_PUBLIC_ENDPOINT_URL_HTTP}
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
      - SUPABASE_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.knhOrPKq1GjejLQr7fuiRBFILwzKxrpxBvzYEJXKy8E
    expose:
      - port: 3000
        as: 80
        to:
          - global: true

  gotrue:
    image: supabase/gotrue:v2.41.0
    depends_on:
      - db
    env:
      - API_EXTERNAL_URL=${AKASH_PUBLIC_ENDPOINT_URL_HTTP}
      - GOTRUE_API_HOST=0.0.0.0
      - GOTRUE_API_PORT=9999
      - GOTRUE_DB_DRIVER=postgres
      - GOTRUE_DB_DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - GOTRUE_SITE_URL=${AKASH_PUBLIC_ENDPOINT_URL_HTTP}
      - GOTRUE_URI_ALLOW_LIST=
      - GOTRUE_DISABLE_SIGNUP=false
      - GOTRUE_JWT_SECRET=super-secret-jwt-token-with-at-least-32-characters
      - GOTRUE_JWT_EXP=3600
      - GOTRUE_JWT_DEFAULT_GROUP_NAME=authenticated
      - GOTRUE_EXTERNAL_EMAIL_ENABLED=false
      - GOTRUE_MAILER_AUTOCONFIRM=true
      - GOTRUE_SMS_AUTOCONFIRM=true
    expose:
      - port: 9999
        to:
          - service: studio
          - service: kong

  realtime:
    image: supabase/realtime:v2.1.0
    depends_on:
      - db
    env:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_AFTER_CONNECT_QUERY=SET search_path TO _realtime
      - PORT=4000
      - JWT_SECRET=super-secret-jwt-token-with-at-least-32-characters
      - SECURE_CHANNELS=false
      - SLOT_NAME=supabase_realtime
      - TEMPORARY_SLOT=true
      - DB_SSL=false
    expose:
      - port: 4000
        to:
          - service: studio
          - service: kong

  storage:
    image: supabase/storage-api:v0.28.0
    depends_on:
      - db
      - api
    env:
      - ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
      - SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.knhOrPKq1GjejLQr7fuiRBFILwzKxrpxBvzYEJXKy8E
      - POSTGREST_URL=http://api:3000
      - PGRST_JWT_SECRET=super-secret-jwt-token-with-at-least-32-characters
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - PGOPTIONS=-c search_path=storage,public
      - FILE_SIZE_LIMIT=50000000
      - STORAGE_BACKEND=file
      - FILE_STORAGE_BACKEND_PATH=/var/lib/storage
      - TENANT_ID=stub
    expose:
      - port: 5000
        to:
          - service: studio
          - service: kong
    params:
      storage:
        storage-files:
          mount: /var/lib/storage

  meta:
    image: supabase/postgres-meta:v0.60.8
    depends_on:
      - db
    env:
      - PG_META_PORT=8080
      - PG_META_DB_HOST=db
      - PG_META_DB_PASSWORD=postgres
      - PG_META_DB_PORT=5432
      - PG_META_DB_NAME=postgres
      - PG_META_DB_USER=postgres
    expose:
      - port: 8080
        to:
          - service: studio

  kong:
    image: kong:2.8.1
    depends_on:
      - api
      - gotrue
      - storage
      - realtime
    env:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong.yml
    expose:
      - port: 8000
        to:
          - service: studio
    cmd:
      - kong
      - start
      - -c
      - /kong.yml

profiles:
  compute:
    db:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 2Gi
        storage:
          size: 10Gi
    api:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
    studio:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
    gotrue:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
    realtime:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
    storage:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 10Gi
    meta:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
    kong:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        db:
          denom: uakt
          amount: 10000
        api:
          denom: uakt
          amount: 5000
        studio:
          denom: uakt
          amount: 5000
        gotrue:
          denom: uakt
          amount: 5000
        realtime:
          denom: uakt
          amount: 5000
        storage:
          denom: uakt
          amount: 5000
        meta:
          denom: uakt
          amount: 5000
        kong:
          denom: uakt
          amount: 5000
deployment:
  db:
    akash:
      profile: db
      count: 1
  api:
    akash:
      profile: api
      count: 1
  studio:
    akash:
      profile: studio
      count: 1
  gotrue:
    akash:
      profile: gotrue
      count: 1
  realtime:
    akash:
      profile: realtime
      count: 1
  storage:
    akash:
      profile: storage
      count: 1
  meta:
    akash:
      profile: meta
      count: 1
  kong:
    akash:
      profile: kong
      count: 1
